name: Deploy Todo in Dev Environment

on:
  push:
    branches:
      - dev

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ezraamos/todo:${{ github.sha }}

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/app/"

      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mv /home/ubuntu/app/docker-compose.yml /var/www/todo/frontend/docker-compose.yml
            cd /var/www/todo/frontend
            sudo echo "IMAGE_TAG=${{ github.sha }}" >> .env
            docker-compose down || true
            docker-compose up -d
            docker image prune -a -f
